"use client";
import { useEffect, useState } from "react";
import { useParams, useRouter } from "next/navigation";
import Link from "next/link";
import { ArrowLeft, Plus, Search } from "lucide-react";
import AppShell from "../../../components/layout/AppShell";
import Modal from "../../../components/ui/Modal";
import Toast from "../../../components/ui/Toast";
import Pagination from "../../../components/tables/Pagination";
import ActionMenu from "../../../components/ui/ActionMenu";
import { api } from "../../../lib/api";
import type { DNSRecord, Page, RecordType, RoutingPolicy, Zone } from "../../../types";

const types: RecordType[] = ["A","AAAA","CNAME","TXT","MX","NS","PTR","SRV","CAA"];
const policies: RoutingPolicy[] = ["Simple","Weighted","Latency","Failover"];

export default function ZonePage() {
  const params = useParams<{zoneId:string}>(); const id = Number(params.zoneId); const router = useRouter();
  const [zone,setZone]=useState<Zone|null>(null); const [data,setData]=useState<Page<DNSRecord>|null>(null); const [search,setSearch]=useState(""); const [page,setPage]=useState(1); const [modal,setModal]=useState<"create"|"edit"|"delete"|null>(null); const [selected,setSelected]=useState<DNSRecord|null>(null); const [toast,setToast]=useState(""); const [error,setError]=useState(""); const [loading,setLoading]=useState(true);
  async function load(){setLoading(true);try{const [z,records]=await Promise.all([api.zone(id),api.records(id,page,search)]);setZone(z);setData(records);setError("");}catch(e){setError(e instanceof Error?e.message:"Unable to load records");}finally{setLoading(false);}}
  useEffect(()=>{if(Number.isFinite(id))void load();},[id,page,search]);
  if(error&&!zone)return <AppShell><div className="card p-8"><h1 className="text-xl font-semibold">Unable to load hosted zone</h1><p className="text-red-700 mt-2">{error}</p><Link href="/hosted-zones" className="aws-link inline-block mt-5">Back to hosted zones</Link></div></AppShell>;
  return <AppShell><div className="max-w-[1500px]">
    <nav className="breadcrumb mb-4" aria-label="Breadcrumb"><Link href="/dashboard">AWS Management Console</Link><span className="mx-2">›</span><Link href="/hosted-zones">Hosted zones</Link><span className="mx-2">›</span><span>{zone?.name || "Hosted zone"}</span></nav>
    <div className="flex flex-wrap justify-between items-end gap-4 mb-5"><div><h1 className="page-title">{zone?.name || "Hosted zone"}</h1><p className="subtle mt-2">Hosted zone ID: <span className="font-mono">{zone?.zone_id || "—"}</span> · {zone?.zone_type || ""}</p></div><button className="btn btn-primary flex items-center gap-2" onClick={()=>{setSelected(null);setModal("create")}}><Plus size={17}/> Create record</button></div>
    <div className="action-bar"><ActionMenu items={[{label:"Create record",onClick:()=>{setSelected(null);setModal("create")}},{label:"Refresh",onClick:()=>void load()}]}/><span className="subtle text-sm">Resource records</span></div>
    <div className="console-panel">
      <div className="console-panel-header flex flex-wrap justify-between items-center gap-3"><span>Records</span><span className="font-normal text-sm subtle">{data?.total ?? 0} records</span></div>
      <div className="p-4 border-b border-[#eaeded] flex items-center gap-3"><div className="relative max-w-xl w-full"><Search className="absolute left-3 top-2.5 text-gray-400" size={17}/><input className="aws-input pl-9" aria-label="Search DNS records" placeholder="Search by record name, type, or value" value={search} onChange={e=>{setPage(1);setSearch(e.target.value)}}/></div></div>
      {error&&<div className="m-4 aws-alert-error">{error}<button className="aws-link ml-3" onClick={()=>void load()}>Retry</button></div>}
      {loading?<div className="empty-state">Loading records…</div>:!data?.items.length?<div className="empty-state"><h2 className="font-semibold text-[#161e2d]">No records found</h2><p className="mt-2">Create a record to manage DNS data for this hosted zone.</p><button className="btn btn-primary mt-5" onClick={()=>{setSelected(null);setModal("create")}}>Create record</button></div>:<><div className="overflow-x-auto"><table className="w-full text-sm aws-table"><thead><tr><th className="p-4 text-left">Record name</th><th className="p-4 text-left">Type</th><th className="p-4 text-left">TTL</th><th className="p-4 text-left">Value / routing</th><th className="p-4 text-left">Actions</th></tr></thead><tbody>{data.items.map(rec=><tr key={rec.id}><td className="p-4 font-semibold">{rec.name}</td><td className="p-4"><span className="font-mono text-xs border border-[#c6c6c6] px-2 py-1 bg-[#f2f3f3]">{rec.type}</span></td><td className="p-4">{rec.ttl}</td><td className="p-4 max-w-2xl"><div className="font-mono text-xs break-all">{rec.value}</div><div className="text-xs subtle mt-1">Routing: {rec.routing_policy}</div></td><td className="p-4"><ActionMenu items={[{label:"Edit",onClick:()=>{setSelected(rec);setModal("edit")}},{label:"Delete",danger:true,onClick:()=>{setSelected(rec);setModal("delete")}}]}/></td></tr>)}</tbody></table></div><div className="p-4 border-t border-[#eaeded]"><Pagination page={data.page} pages={data.pages} onChange={setPage}/></div></>}
    </div><button className="btn mt-5 flex items-center gap-2" onClick={()=>router.push('/hosted-zones')}><ArrowLeft size={16}/> Back to hosted zones</button>
  </div>{modal&&<RecordModal mode={modal} record={selected||undefined} zoneId={id} close={()=>setModal(null)} refresh={load} toast={setToast}/>} {toast&&<Toast message={toast} onClose={()=>setToast("")}/>}</AppShell>;
}

function RecordModal({mode,record,zoneId,close,refresh,toast}:{mode:"create"|"edit"|"delete";record?:DNSRecord;zoneId:number;close:()=>void;refresh:()=>Promise<void>;toast:(s:string)=>void}){
  const [name,setName]=useState(record?.name||""); const [type,setType]=useState<RecordType>(record?.type||"A"); const [ttl,setTtl]=useState(String(record?.ttl||300)); const [value,setValue]=useState(record?.value||""); const [routing,setRouting]=useState<RoutingPolicy>(record?.routing_policy||"Simple"); const [busy,setBusy]=useState(false); const [error,setError]=useState("");
  async function save(){setBusy(true);setError("");try{if(mode==='delete'){await api.deleteRecord(record!.id);toast('Record deleted successfully.')}else{const body={name,type,ttl:Number(ttl),value,routing_policy:routing};if(mode==='create')await api.createRecord(zoneId,body);else await api.updateRecord(record!.id,body);toast(mode==='create'?'Record created successfully.':'Record updated successfully.')}close();await refresh();}catch(e){setError(e instanceof Error?e.message:'Request failed');}finally{setBusy(false)}}
  return <Modal title={mode==='delete'?'Delete record':mode==='create'?'Create record':'Edit record'} onClose={close}>{mode==='delete'?<><p>Delete record <strong>{record?.name} ({record?.type})</strong>? This cannot be undone.</p>{error&&<div className="aws-alert-error mt-4">{error}</div>}<div className="flex justify-end gap-3 mt-7"><button className="btn" onClick={close}>Cancel</button><button className="btn bg-[#d91515] text-white border-[#d91515]" disabled={busy} onClick={()=>void save()}>{busy?'Deleting…':'Delete'}</button></div></>:<div className="space-y-5"><div className="bg-[#f2f3f3] border border-[#d5dbdb] p-4 text-sm"><strong>Record details</strong><p className="subtle mt-1">Enter the DNS resource record values used by this fictional Route 53 environment.</p></div><label className="aws-label">Record name *<input required className="aws-input mt-1" value={name} onChange={e=>setName(e.target.value)} placeholder="www.example.com"/></label><div className="grid grid-cols-1 sm:grid-cols-2 gap-4"><label className="aws-label">Record type<select className="aws-input mt-1" value={type} onChange={e=>setType(e.target.value as RecordType)}>{types.map(t=><option key={t}>{t}</option>)}</select></label><label className="aws-label">TTL (seconds)<input type="number" min="1" max="86400" className="aws-input mt-1" value={ttl} onChange={e=>setTtl(e.target.value)}/></label></div><label className="aws-label">Value *<textarea required className="aws-input mt-1 min-h-28 font-mono text-sm" value={value} onChange={e=>setValue(e.target.value)} placeholder={placeholderFor(type)}/></label><label className="aws-label">Routing policy<select className="aws-input mt-1" value={routing} onChange={e=>setRouting(e.target.value as RoutingPolicy)}>{policies.map(p=><option key={p}>{p}</option>)}</select></label>{error&&<div className="aws-alert-error" role="alert">{error}</div>}<div className="flex justify-end gap-3"><button className="btn" onClick={close}>Cancel</button><button className="btn btn-primary" disabled={busy||!name.trim()||!value.trim()||Number(ttl)<1} onClick={()=>void save()}>{busy?'Saving…':mode==='create'?'Create record':'Save changes'}</button></div></div>}</Modal>;
}
function placeholderFor(type:RecordType){return {A:"192.0.2.10",AAAA:"2001:db8::10",CNAME:"target.example.com",TXT:'"text value"',MX:"10 mail.example.com",NS:"ns1.example.com",PTR:"host.example.com",SRV:"10 5 443 service.example.com",CAA:'0 issue "letsencrypt.org"'}[type];}
